vich_uploader:
    db_driver: orm
    mappings:
        cours_pdfs:
            uri_prefix: '%app.path.cours_pdfs%'
            upload_destination: '%kernel.project_dir%/public/uploads/pdf/cours'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

        cours:
            uri_prefix: /pdf/cours
            upload_destination: '%kernel.project_dir%/public/uploads/pdf/cours'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
